"""init

Revision ID: dbaab40ed659
Revises:
Create Date: 2025-07-31 23:00:02.373719

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dbaab40ed659"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
